### ISSUE TITLE
Support BigQuery upload of BigDiffy results

### ISSUE THREAD

**Issue by tkhduracell** [spotify/ratatool#106]
The bigdiffy tool is great but isn't very user-friendly. It's great that is can do diffs on BigQuery tables, but it is a bit cumbersome that the results are written to GCS, also without any schema. 

I suggest that we change the CLI API so that one can choose the write results to either GCS or BQ. 
```
big-diffy --runner=DataflowRunner <stuff> --key=record_id --lhs=bq://<dataset1> --rhs=bq://<dataset2> --output=bq://project/dataset/table
```

Also it would be nice to auto infer mode=bigquery in this case. When lhs and rhs has bq:// prefix.

**Comment by tkhduracell** [comment]
@idreeskhan

**Comment by idreeskhan** [comment]
Implementation off the top of my head can look roughly like:
```
- [ ] Update BigDiffy saveStats to support writing to BQ
- [ ] Update CLI parsing to distinguish between writing to BQ/GCS for output
```

**Comment by anne-decusatis** [comment]
some progress at https://github.com/anne-decusatis/ratatool/tree/bigquery_upload_bigdiffy_results
