### ISSUE TITLE
BigSample to support "key-wise" samples

### ISSUE THREAD

**Issue by tkhduracell** [spotify/ratatool#107]
I have a use case of provide sampled test data for pipelines. Would be perfect if big-sample could support samples based on keys. I have a table of events attributed to users based on a key and I would like to sample out a set of users and all their events. 

**Input**
```
userid,event
U1, Event1
U1, Event2
U2, Event3
U3, Event4
U3, Event5
U4, Event6
U2, Event7
```

**CLI**
```
bin/ratatool bigSampler bigquery --head -n 2 --in project_id:dataset_id.table_id \
    --out out.json --key=userid
```

**Output**
```
userid,event
U1, Event1
U1, Event2
U3, Event4
U3, Event5
```

**Comment by idreeskhan** [comment]
This should be achievable at the moment using `fields` (also `seed` if necessary).

```
bin/ratatool bigSampler bigquery --head -n 2 --in project_id:dataset_id.table_id \
    --out out.json--tableOut project_id:dataset_id.table_id --fields=userid
```

If you need to key on (user_id, other_field) it will be `fields=userid,other_field`

**Comment by tkhduracell** [comment]
I will investigate if this fits my need :)
