### ISSUE TITLE
Add option to ignore NaN in bigDiffy delta

### ISSUE THREAD

**Issue by drubinstein** [spotify/ratatool#177]
When running bigDiffy in some cases I'll have a `NaN` in one side and `0` in the other. The delta of these two values is `NaN. When the mean gets calculated these `NaN`s turn the mean into `NaN` preventing me from analyzing the output of BigDiffy.

Would it be possible to add an option to either turn `NaN` to `0` or ignore rows with `NaN`?

@idreeskhan

**Comment by idreeskhan** [comment]
I think it makes sense to support this as opt-in. Could be supported as both a CLI flag and fn param and off by default (I don't want silent failures if NaN is not expected). What do you think?

**Comment by idreeskhan** [comment]
Whether we ignore or default to 0 I think is up for discussion

**Comment by danielblazevski** [comment]
Fixed in https://github.com/spotify/ratatool/pull/202

We added a flag that will allow one to say they want to ignore NaN values when computing the field stats.
