### ISSUE TITLE
Use farmhash instead of murmur for BigSampler

### ISSUE THREAD

**Issue by ravwojdyla** [spotify/ratatool#24]
https://github.com/google/farmhash is available in guava, this would allow us to use build in hashing in BigQuery (https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#farm_fingerprint).

**Comment by anne-decusatis** [comment]
https://google.github.io/guava/releases/23.0/api/docs/com/google/common/hash/Hashing.html#farmHashFingerprint64-- says: "FarmHashFingerprints generated using this are byte-wise identical to those created using the C++ version, but note that this uses unsigned integers (see UnsignedInts). Comparisons between the two should take this into account."

The BigQuery examples which use FarmHash have both negative and positive numbers returned (though of course I do not know whether it uses C++ or Java or something else entirely under the hood). 

I will investigate more to make sure that the BigQuery farmhash fingerprints are actually comparable to the Guava farmhash fingerprints before implementing.

**Comment by anne-decusatis** [comment]
in Guava: 
```
scala> Hashing.farmHashFingerprint64().newHasher().putString("test", Charset.forName("utf-8")).hash.asLong
res14: Long = 8581389452482819506
```

in BigQuery:
```select farm_fingerprint("test");```
```

Row | f0_ |  
-- | -- | --
1 | 8581389452482819506 |  
```

These look the same to me!

**Comment by idreeskhan** [comment]
If they are bytewise identical it should not matter much. Have you found a case where BQ returns a negative? Would be interesting to see what is produced by a mod operation on that since that is how we would be using it.

**Comment by idreeskhan** [comment]
Best to proceed as is since we want it to produce the same output as BQ
