### ISSUE TITLE
Remove Beam dependency from Ratatool-scalacheck

### ISSUE THREAD

**Issue by idreeskhan** [spotify/ratatool#46]
https://github.com/spotify/ratatool/pull/43/files/8c7130cf6d52d2f11345d0d7f60d5743f3261c47#diff-fdc3abdfd754eeb24090dbd90aeec2ceR205

Look into cleaning up Beam dependency and using Kryo instead of CoderUtils in tests and what the effect of this will be.

**Comment by RustedBones** [comment]
Fixed by #691
