### ISSUE TITLE
Consistency across ProtoBuf and Avro generators

### ISSUE THREAD

**Issue by annaks** [spotify/ratatool#66]
In the past, creating a sample of either ProtoBuf or Avro types followed the same pattern:
`val r = ProtoBufGenerator.protoBufOf[Foo]` and
`val r = AvroGenerator.avroOf[Foo]`.

This has changed in `v0.3.0-beta1` to:
`val r = ProtoBufGeneratorOps.protoBufOf[Foo].sample.get` and
`val r = AvroGeneratorOps.specificRecordOf[Foo].sample.get`
where the methods on generator objects now diverge.

It would be nice if access patterns remain consistent

**Comment by idreeskhan** [comment]
Likely will change to just be aliases of `specificRecordOf`, `genericRecordOf`
